"""update_asset_model_for_caching

Revision ID: 00378f081347
Revises: 7fc34cbfbd64
Create Date: 2026-09-04 16:18:54.064456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00378f081347'
down_revision: Union[str, Sequence[str], None] = '7fc34cbfbd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('source_asset_id', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.alter_column('assets', 'script_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_assets_source_asset_id'), 'assets', ['source_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_source_asset_id'), table_name='assets')
    op.alter_column('assets', 'script_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assets', 'thumbnail_url')
    op.drop_column('assets', 'source_asset_id')
    # ### end Alembic commands ###
