"""update_asset_model_for_caching

Revision ID: 00378f081347
Revises: 7fc34cbfbd64
Create Date: 2026-09-04 16:18:54.064456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00378f081347"
down_revision: Union[str, Sequence[str], None] = "7fc34cbfbd64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("source_asset_id", sa.String(), nullable=True))
    op.add_column("assets", sa.Column("thumbnail_url", sa.String(), nullable=True))
    op.alter_column("assets", "script_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(
        op.f("ix_assets_source_asset_id"), "assets", ["source_asset_id"], unique=False
    )
    op.create_table(
        "daily_compute_spend",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("amount_spent_usd", sa.Float(), nullable=True),
        sa.Column("budget_cap_usd", sa.Float(), nullable=True),
        sa.Column("jobs_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_compute_spend_date"),
        "daily_compute_spend",
        ["date"],
        unique=False,
    )

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("capability", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("worker_id", sa.String(), nullable=True),
        sa.Column("worker_type", sa.String(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_capability"), "jobs", ["capability"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_capability"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_daily_compute_spend_date"), table_name="daily_compute_spend")
    op.drop_table("daily_compute_spend")
    op.drop_index(op.f("ix_assets_source_asset_id"), table_name="assets")
    op.alter_column("assets", "script_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("assets", "thumbnail_url")
    op.drop_column("assets", "source_asset_id")
    # ### end Alembic commands ###
