"""move_channel_settings

Revision ID: 16ee20e4233a
Revises: f0412d529f7e
Create Date: 2026-09-11 22:08:10.948430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ee20e4233a'
down_revision: Union[str, Sequence[str], None] = 'f0412d529f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('default_cta', sa.Text(), nullable=True))
    op.add_column('channels', sa.Column('caption_style', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('watermark_enabled', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('watermark_opacity', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('watermark_position', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('watermark_scale', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('default_voice_id', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('content_tone', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('niche_keywords', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('title_style_preference', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('hashtag_set', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('auto_approve', sa.Boolean(), nullable=True))
    op.drop_column('users', 'auto_approve')
    op.drop_column('users', 'hashtag_set')
    op.drop_column('users', 'default_niche')
    op.drop_column('users', 'content_tone')
    op.drop_column('users', 'watermark_position')
    op.drop_column('users', 'default_voice_id')
    op.drop_column('users', 'niche_keywords')
    op.drop_column('users', 'caption_style')
    op.drop_column('users', 'watermark_opacity')
    op.drop_column('users', 'watermark_scale')
    op.drop_column('users', 'title_style_preference')
    op.drop_column('users', 'default_cta')
    op.drop_column('users', 'watermark_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('watermark_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('default_cta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('title_style_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('watermark_scale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('watermark_opacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('caption_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('niche_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('default_voice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('watermark_position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('content_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('default_niche', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashtag_set', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auto_approve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('channels', 'auto_approve')
    op.drop_column('channels', 'hashtag_set')
    op.drop_column('channels', 'title_style_preference')
    op.drop_column('channels', 'niche_keywords')
    op.drop_column('channels', 'content_tone')
    op.drop_column('channels', 'default_voice_id')
    op.drop_column('channels', 'watermark_scale')
    op.drop_column('channels', 'watermark_position')
    op.drop_column('channels', 'watermark_opacity')
    op.drop_column('channels', 'watermark_enabled')
    op.drop_column('channels', 'caption_style')
    op.drop_column('channels', 'default_cta')
    # ### end Alembic commands ###
