"""Add tenant_id to all models for multi-tenancy and AnalyticsSnapshot

Revision ID: 1aa304cb059a
Revises: 00378f081347
Create Date: 2026-09-04 16:52:53.585580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa304cb059a'
down_revision: Union[str, Sequence[str], None] = '00378f081347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_tenant_id'), 'analytics_snapshots', ['tenant_id'], unique=False)
    op.add_column('analytics', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_analytics_tenant_id'), 'analytics', ['tenant_id'], unique=False)
    op.add_column('assets', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.add_column('channels', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_channels_tenant_id'), 'channels', ['tenant_id'], unique=False)
    op.add_column('ideas', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ideas_tenant_id'), 'ideas', ['tenant_id'], unique=False)
    op.add_column('publications', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_publications_tenant_id'), 'publications', ['tenant_id'], unique=False)
    op.add_column('scenes', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_scenes_tenant_id'), 'scenes', ['tenant_id'], unique=False)
    op.add_column('scripts', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_scripts_tenant_id'), 'scripts', ['tenant_id'], unique=False)
    op.add_column('videos', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_tenant_id'), 'videos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_tenant_id'), table_name='videos')
    op.drop_column('videos', 'tenant_id')
    op.drop_index(op.f('ix_scripts_tenant_id'), table_name='scripts')
    op.drop_column('scripts', 'tenant_id')
    op.drop_index(op.f('ix_scenes_tenant_id'), table_name='scenes')
    op.drop_column('scenes', 'tenant_id')
    op.drop_index(op.f('ix_publications_tenant_id'), table_name='publications')
    op.drop_column('publications', 'tenant_id')
    op.drop_index(op.f('ix_ideas_tenant_id'), table_name='ideas')
    op.drop_column('ideas', 'tenant_id')
    op.drop_index(op.f('ix_channels_tenant_id'), table_name='channels')
    op.drop_column('channels', 'tenant_id')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_column('assets', 'tenant_id')
    op.drop_index(op.f('ix_analytics_tenant_id'), table_name='analytics')
    op.drop_column('analytics', 'tenant_id')
    op.drop_index(op.f('ix_analytics_snapshots_tenant_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
