"""channel_intelligence_and_video_format

Revision ID: 1b17392c0e1d
Revises: a2e39e32896a
Create Date: 2026-10-01 20:48:30.106051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b17392c0e1d"
down_revision: Union[str, Sequence[str], None] = "a2e39e32896a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("content_pillars", sa.JSON(), nullable=True))
    op.add_column("channels", sa.Column("target_audience", sa.String(), nullable=True))
    op.add_column("channels", sa.Column("excluded_topics", sa.JSON(), nullable=True))
    op.add_column("channels", sa.Column("excluded_keywords", sa.JSON(), nullable=True))
    op.add_column("channels", sa.Column("recent_topics", sa.JSON(), nullable=True))
    op.add_column(
        "channels", sa.Column("previously_used_topics", sa.JSON(), nullable=True)
    )
    op.add_column(
        "channels", sa.Column("preferred_content_formats", sa.JSON(), nullable=True)
    )
    op.add_column("channels", sa.Column("visual_preferences", sa.JSON(), nullable=True))
    op.add_column("channels", sa.Column("topic_fingerprints", sa.JSON(), nullable=True))
    op.add_column(
        "channels", sa.Column("performance_metrics", sa.JSON(), nullable=True)
    )
    op.add_column("videos", sa.Column("error_code", sa.String(), nullable=True))
    op.add_column("videos", sa.Column("content_type", sa.String(), nullable=True))
    op.add_column(
        "videos", sa.Column("target_duration_seconds", sa.Integer(), nullable=True)
    )
    op.add_column("videos", sa.Column("orientation", sa.String(), nullable=True))
    op.add_column("videos", sa.Column("visual_strategy", sa.String(), nullable=True))
    op.add_column("videos", sa.Column("duration_mode", sa.String(), nullable=True))
    op.add_column("videos", sa.Column("render_metadata", sa.JSON(), nullable=True))
    op.add_column("videos", sa.Column("selected_voice", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "selected_voice")
    op.drop_column("videos", "render_metadata")
    op.drop_column("videos", "duration_mode")
    op.drop_column("videos", "visual_strategy")
    op.drop_column("videos", "orientation")
    op.drop_column("videos", "target_duration_seconds")
    op.drop_column("videos", "content_type")
    op.drop_column("videos", "error_code")
    op.drop_column("channels", "performance_metrics")
    op.drop_column("channels", "topic_fingerprints")
    op.drop_column("channels", "visual_preferences")
    op.drop_column("channels", "preferred_content_formats")
    op.drop_column("channels", "previously_used_topics")
    op.drop_column("channels", "recent_topics")
    op.drop_column("channels", "excluded_keywords")
    op.drop_column("channels", "excluded_topics")
    op.drop_column("channels", "target_audience")
    op.drop_column("channels", "content_pillars")
    # ### end Alembic commands ###
