"""Add multi-platform support to Publication model

Revision ID: 604877c2578a
Revises: 1b17392c0e1d
Create Date: 2026-10-03 21:47:43.029788

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "604877c2578a"
down_revision: Union[str, Sequence[str], None] = "1b17392c0e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instagram_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("ig_user_id", sa.String(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instagram_connections_user_id"),
        "instagram_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tiktok_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("open_id", sa.String(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tiktok_connections_user_id"),
        "tiktok_connections",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "ideas",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column("publications", sa.Column("tiktok_id", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("instagram_id", sa.String(), nullable=True))
    op.add_column("publications", sa.Column("platforms", sa.JSON(), nullable=True))
    op.add_column(
        "publications",
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "publications", sa.Column("schedule_status", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "schedule_status")
    op.drop_column("publications", "scheduled_at")
    op.drop_column("publications", "platforms")
    op.drop_column("publications", "instagram_id")
    op.drop_column("publications", "tiktok_id")
    op.alter_column(
        "ideas",
        "settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_tiktok_connections_user_id"), table_name="tiktok_connections"
    )
    op.drop_table("tiktok_connections")
    op.drop_index(
        op.f("ix_instagram_connections_user_id"), table_name="instagram_connections"
    )
    op.drop_table("instagram_connections")
    # ### end Alembic commands ###
