"""Initial Neon Postgres migration

Revision ID: 61b87d7eb806
Revises: 
Create Date: 2026-09-03 18:58:01.034130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b87d7eb806'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('niche', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('default_cta', sa.Text(), nullable=True),
    sa.Column('default_niche', sa.String(), nullable=True),
    sa.Column('caption_style', sa.String(), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=True),
    sa.Column('watermark_opacity', sa.Float(), nullable=True),
    sa.Column('watermark_position', sa.String(), nullable=True),
    sa.Column('watermark_scale', sa.Float(), nullable=True),
    sa.Column('default_voice_id', sa.String(), nullable=True),
    sa.Column('content_tone', sa.String(), nullable=True),
    sa.Column('niche_keywords', sa.JSON(), nullable=True),
    sa.Column('title_style_preference', sa.String(), nullable=True),
    sa.Column('hashtag_set', sa.JSON(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'scripted', name='ideastatus'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('payoff', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('visual_prompts', sa.JSON(), nullable=True),
    sa.Column('duration_est', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('fact_check_ok', sa.Boolean(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('commercial_ok', sa.Boolean(), nullable=True),
    sa.Column('attribution_req', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('caption_style', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rendering', 'ready', 'approved', 'rejected', 'uploaded', 'failed', 'publish_failed', name='videostatus'), nullable=True),
    sa.Column('ai_used', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('title_candidates', sa.JSON(), nullable=True),
    sa.Column('selected_title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('voice_override', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('youtube_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('privacy_status', sa.Enum('private', 'unlisted', 'public', name='privacystatus'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('analytics')
    op.drop_table('videos')
    op.drop_table('assets')
    op.drop_table('scripts')
    op.drop_table('ideas')
    op.drop_table('user_profiles')
    op.drop_table('channels')
    # ### end Alembic commands ###
