"""Add tiktok_id and instagram_id to publications

Revision ID: 65a1fbefef5b
Revises: 604877c2578a
Create Date: 2026-10-03 21:55:45.504603

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65a1fbefef5b"
down_revision: Union[str, Sequence[str], None] = "604877c2578a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
