"""add_render_stage_to_video

Revision ID: 7fc34cbfbd64
Revises: 14c2e35df3a7
Create Date: 2026-09-04 15:55:12.203510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc34cbfbd64'
down_revision: Union[str, Sequence[str], None] = '14c2e35df3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('render_stage', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('render_progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'render_progress')
    op.drop_column('videos', 'render_stage')
    # ### end Alembic commands ###
