"""Add cost_events

Revision ID: 98c97eef9cc3
Revises: 99a120c4ad89
Create Date: 2026-09-16 17:24:16.467914

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98c97eef9cc3"
down_revision: Union[str, Sequence[str], None] = "99a120c4ad89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_events_channel_id"), "cost_events", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_events_job_id"), "cost_events", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_events_stage"), "cost_events", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_cost_events_user_id"), "cost_events", ["user_id"], unique=False
    )
    op.execute("DELETE FROM daily_compute_spend")
    op.add_column(
        "daily_compute_spend", sa.Column("user_id", sa.String(), nullable=False)
    )
    op.drop_index(op.f("ix_daily_compute_spend_date"), table_name="daily_compute_spend")
    op.create_index(
        op.f("ix_daily_compute_spend_date"),
        "daily_compute_spend",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_compute_spend_user_id"),
        "daily_compute_spend",
        ["user_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_date", "daily_compute_spend", ["user_id", "date"]
    )
    op.create_foreign_key(
        None, "daily_compute_spend", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "daily_compute_spend", type_="foreignkey")
    op.drop_constraint("uq_user_date", "daily_compute_spend", type_="unique")
    op.drop_index(
        op.f("ix_daily_compute_spend_user_id"), table_name="daily_compute_spend"
    )
    op.drop_index(op.f("ix_daily_compute_spend_date"), table_name="daily_compute_spend")
    op.create_index(
        op.f("ix_daily_compute_spend_date"),
        "daily_compute_spend",
        ["date"],
        unique=True,
    )
    op.drop_column("daily_compute_spend", "user_id")
    op.drop_index(op.f("ix_cost_events_user_id"), table_name="cost_events")
    op.drop_index(op.f("ix_cost_events_stage"), table_name="cost_events")
    op.drop_index(op.f("ix_cost_events_job_id"), table_name="cost_events")
    op.drop_index(op.f("ix_cost_events_channel_id"), table_name="cost_events")
    op.drop_table("cost_events")
    # ### end Alembic commands ###
