"""add password_hash to user

Revision ID: 993d56d6e09c
Revises: 98c97eef9cc3
Create Date: 2026-09-24 16:38:04.408279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "993d56d6e09c"
down_revision: Union[str, Sequence[str], None] = "98c97eef9cc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("preferred_ai_provider", sa.String(), nullable=True)
    )
    op.add_column("users", sa.Column("preferred_ai_model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferred_ai_model")
    op.drop_column("users", "preferred_ai_provider")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
