"""durable_job_model

Revision ID: 99a120c4ad89
Revises: 16ee20e4233a
Create Date: 2026-09-16 14:24:51.456961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99a120c4ad89"
down_revision: Union[str, Sequence[str], None] = "16ee20e4233a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        bind.execute(
            sa.text(
                "CREATE TYPE pipelinestage AS ENUM ('RESEARCH', 'SCRIPT', 'ASSETS', 'VOICE', 'TIMELINE', 'RENDER', 'QA', 'UPLOAD', 'PUBLISH', 'ANALYTICS')"
            )
        )
        bind.execute(
            sa.text(
                "CREATE TYPE jobstatus AS ENUM ('CREATED', 'QUEUED', 'CLAIMED', 'RUNNING', 'PAUSED', 'RETRYING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'DEAD_LETTER')"
            )
        )
        # Map existing old statuses to new enum values
        bind.execute(sa.text("UPDATE jobs SET status = UPPER(status)"))
        bind.execute(
            sa.text("UPDATE jobs SET status = 'SUCCEEDED' WHERE status = 'COMPLETED'")
        )
        bind.execute(
            sa.text("UPDATE jobs SET status = 'FAILED' WHERE status = 'ERROR'")
        )
        bind.execute(
            sa.text("UPDATE jobs SET status = 'RUNNING' WHERE status = 'PROCESSING'")
        )
        bind.execute(
            sa.text("UPDATE jobs SET status = 'QUEUED' WHERE status = 'PENDING'")
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("channel_id", sa.String(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "current_stage",
            sa.Enum(
                "RESEARCH",
                "SCRIPT",
                "ASSETS",
                "VOICE",
                "TIMELINE",
                "RENDER",
                "QA",
                "UPLOAD",
                "PUBLISH",
                "ANALYTICS",
                name="pipelinestage",
            ),
            nullable=True,
        ),
    )
    op.add_column("jobs", sa.Column("priority", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("attempt_number", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("max_attempts", sa.Integer(), nullable=True))
    op.add_column(
        "jobs", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("jobs", sa.Column("idempotency_key", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("input_version", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("output_version", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("error_code", sa.String(), nullable=True))
    op.alter_column(
        "jobs",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "CREATED",
            "QUEUED",
            "CLAIMED",
            "RUNNING",
            "PAUSED",
            "RETRYING",
            "SUCCEEDED",
            "FAILED",
            "CANCELLED",
            "DEAD_LETTER",
            name="jobstatus",
        ),
        existing_nullable=True,
        postgresql_using="status::jobstatus",
    )
    op.create_index(op.f("ix_jobs_channel_id"), "jobs", ["channel_id"], unique=False)
    op.create_index(
        op.f("ix_jobs_idempotency_key"), "jobs", ["idempotency_key"], unique=False
    )
    op.create_foreign_key(
        None, "jobs", "channels", ["channel_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_idempotency_key"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_channel_id"), table_name="jobs")
    op.alter_column(
        "jobs",
        "status",
        existing_type=sa.Enum(
            "CREATED",
            "QUEUED",
            "CLAIMED",
            "RUNNING",
            "PAUSED",
            "RETRYING",
            "SUCCEEDED",
            "FAILED",
            "CANCELLED",
            "DEAD_LETTER",
            name="jobstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("jobs", "error_code")
    op.drop_column("jobs", "output_version")
    op.drop_column("jobs", "input_version")
    op.drop_column("jobs", "idempotency_key")
    op.drop_column("jobs", "lease_expires_at")
    op.drop_column("jobs", "heartbeat_at")
    op.drop_column("jobs", "scheduled_at")
    op.drop_column("jobs", "max_attempts")
    op.drop_column("jobs", "attempt_number")
    op.drop_column("jobs", "priority")
    op.drop_column("jobs", "current_stage")
    op.drop_column("jobs", "channel_id")
    # ### end Alembic commands ###
