"""add_promoted_to_ideastatus

Revision ID: a2e39e32896a
Revises: 993d56d6e09c
Create Date: 2026-09-24 19:52:44.472715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2e39e32896a"
down_revision: Union[str, Sequence[str], None] = "993d56d6e09c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE ideastatus ADD VALUE IF NOT EXISTS 'promoted'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
