"""add tiktok_id and instagram_id to publications

Revision ID: b643b3003b29
Revises: 65a1fbefef5b
Create Date: 2026-10-04 21:11:31.978760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b643b3003b29"
down_revision: Union[str, Sequence[str], None] = "65a1fbefef5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
