"""Multi-tenant schema

Revision ID: d3b52304dc4c
Revises: 1aa304cb059a
Create Date: 2026-09-11 15:29:57.166938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3b52304dc4c'
down_revision: Union[str, Sequence[str], None] = '1aa304cb059a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('default_cta', sa.Text(), nullable=True),
    sa.Column('default_niche', sa.String(), nullable=True),
    sa.Column('caption_style', sa.String(), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=True),
    sa.Column('watermark_opacity', sa.Float(), nullable=True),
    sa.Column('watermark_position', sa.String(), nullable=True),
    sa.Column('watermark_scale', sa.Float(), nullable=True),
    sa.Column('default_voice_id', sa.String(), nullable=True),
    sa.Column('content_tone', sa.String(), nullable=True),
    sa.Column('niche_keywords', sa.JSON(), nullable=True),
    sa.Column('title_style_preference', sa.String(), nullable=True),
    sa.Column('hashtag_set', sa.JSON(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.execute("INSERT INTO users (id, display_name) VALUES ('default-user', 'Default User')")
    op.create_table('youtube_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_connections_user_id'), 'youtube_connections', ['user_id'], unique=False)
    op.drop_table('user_profiles')
    op.add_column('analytics', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('analytics', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_analytics_tenant_id'), table_name='analytics')
    op.create_index(op.f('ix_analytics_user_id'), 'analytics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'analytics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analytics', 'tenant_id')
    op.add_column('analytics_snapshots', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('analytics_snapshots', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_analytics_snapshots_tenant_id'), table_name='analytics_snapshots')
    op.create_index(op.f('ix_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'analytics_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analytics_snapshots', 'tenant_id')
    op.add_column('assets', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assets', 'tenant_id')
    op.add_column('channels', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_channels_tenant_id'), table_name='channels')
    op.create_index(op.f('ix_channels_user_id'), 'channels', ['user_id'], unique=False)
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('channels', 'tenant_id')
    op.alter_column('daily_compute_spend', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('daily_compute_spend', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('ideas', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_ideas_tenant_id'), table_name='ideas')
    op.create_index(op.f('ix_ideas_user_id'), 'ideas', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ideas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ideas', 'tenant_id')
    op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'tenant_id')
    op.add_column('publications', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('publications', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_publications_tenant_id'), table_name='publications')
    op.create_index(op.f('ix_publications_user_id'), 'publications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'publications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('publications', 'tenant_id')
    op.add_column('scenes', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_scenes_tenant_id'), table_name='scenes')
    op.create_index(op.f('ix_scenes_user_id'), 'scenes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scenes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scenes', 'tenant_id')
    op.add_column('scripts', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('scripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_scripts_tenant_id'), table_name='scripts')
    op.create_index(op.f('ix_scripts_user_id'), 'scripts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scripts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scripts', 'tenant_id')
    op.add_column('videos', sa.Column('user_id', sa.String(), nullable=False, server_default='default-user'))
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_videos_tenant_id'), table_name='videos')
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.create_foreign_key(None, 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('videos', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.create_index(op.f('ix_videos_tenant_id'), 'videos', ['tenant_id'], unique=False)
    op.alter_column('videos', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('videos', 'user_id')
    op.add_column('scripts', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_index(op.f('ix_scripts_user_id'), table_name='scripts')
    op.create_index(op.f('ix_scripts_tenant_id'), 'scripts', ['tenant_id'], unique=False)
    op.alter_column('scripts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('scripts', 'user_id')
    op.add_column('scenes', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_index(op.f('ix_scenes_user_id'), table_name='scenes')
    op.create_index(op.f('ix_scenes_tenant_id'), 'scenes', ['tenant_id'], unique=False)
    op.alter_column('scenes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('scenes', 'user_id')
    op.add_column('publications', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_index(op.f('ix_publications_user_id'), table_name='publications')
    op.create_index(op.f('ix_publications_tenant_id'), 'publications', ['tenant_id'], unique=False)
    op.alter_column('publications', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('publications', 'user_id')
    op.add_column('jobs', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.alter_column('jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('jobs', 'user_id')
    op.add_column('ideas', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.drop_index(op.f('ix_ideas_user_id'), table_name='ideas')
    op.create_index(op.f('ix_ideas_tenant_id'), 'ideas', ['tenant_id'], unique=False)
    op.alter_column('ideas', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('ideas', 'user_id')
    op.alter_column('daily_compute_spend', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('daily_compute_spend', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('channels', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_index(op.f('ix_channels_user_id'), table_name='channels')
    op.create_index(op.f('ix_channels_tenant_id'), 'channels', ['tenant_id'], unique=False)
    op.alter_column('channels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('channels', 'user_id')
    op.add_column('assets', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.alter_column('assets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('assets', 'user_id')
    op.add_column('analytics_snapshots', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analytics_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.create_index(op.f('ix_analytics_snapshots_tenant_id'), 'analytics_snapshots', ['tenant_id'], unique=False)
    op.alter_column('analytics_snapshots', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('analytics_snapshots', 'user_id')
    op.add_column('analytics', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_user_id'), table_name='analytics')
    op.create_index(op.f('ix_analytics_tenant_id'), 'analytics', ['tenant_id'], unique=False)
    op.alter_column('analytics', 'recorded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('analytics', 'user_id')
    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_cta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_niche', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caption_style', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('watermark_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('watermark_opacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('watermark_position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('watermark_scale', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('default_voice_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_tone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('niche_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('title_style_preference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashtag_set', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('auto_approve', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    op.drop_index(op.f('ix_youtube_connections_user_id'), table_name='youtube_connections')
    op.drop_table('youtube_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
