"""auto_scheduler_config

Revision ID: d90c6b495b4e
Revises: b643b3003b29
Create Date: 2026-10-05 17:45:03.467380

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d90c6b495b4e"
down_revision: Union[str, Sequence[str], None] = "b643b3003b29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("schedule_config", sa.JSON(), nullable=True))
    op.add_column(
        "publications", sa.Column("platform_connection_id", sa.String(), nullable=True)
    )
    op.add_column(
        "publications",
        sa.Column("platform", sa.String(), server_default="youtube", nullable=False),
    )
    op.add_column(
        "publications", sa.Column("remote_media_id", sa.String(), nullable=True)
    )
    op.add_column("publications", sa.Column("caption", sa.Text(), nullable=True))
    op.add_column("publications", sa.Column("hashtags", sa.JSON(), nullable=True))
    op.add_column("publications", sa.Column("attempts", sa.Integer(), nullable=True))
    op.add_column("publications", sa.Column("last_error", sa.Text(), nullable=True))
    op.add_column(
        "publications", sa.Column("platform_metadata", sa.JSON(), nullable=True)
    )
    op.add_column(
        "publications", sa.Column("idempotency_key", sa.String(), nullable=True)
    )
    op.drop_constraint(
        op.f("publications_video_id_key"), "publications", type_="unique"
    )
    op.create_index(
        op.f("ix_publications_idempotency_key"),
        "publications",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publications_video_id"), "publications", ["video_id"], unique=False
    )
    op.drop_column("publications", "youtube_id")
    op.drop_column("publications", "platforms")
    op.drop_column("publications", "tiktok_id")
    op.drop_column("publications", "instagram_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publications",
        sa.Column("instagram_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "publications",
        sa.Column("tiktok_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "publications",
        sa.Column(
            "platforms",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "publications",
        sa.Column("youtube_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_publications_video_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_idempotency_key"), table_name="publications")
    op.create_unique_constraint(
        op.f("publications_video_id_key"),
        "publications",
        ["video_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("publications", "idempotency_key")
    op.drop_column("publications", "platform_metadata")
    op.drop_column("publications", "last_error")
    op.drop_column("publications", "attempts")
    op.drop_column("publications", "hashtags")
    op.drop_column("publications", "caption")
    op.drop_column("publications", "remote_media_id")
    op.drop_column("publications", "platform")
    op.drop_column("publications", "platform_connection_id")
    op.drop_column("channels", "schedule_config")
    # ### end Alembic commands ###
