"""lifecycle_states

Revision ID: de47fccac0ec
Revises: 61b87d7eb806
Create Date: 2026-09-04 13:28:24.139298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de47fccac0ec'
down_revision: Union[str, Sequence[str], None] = '61b87d7eb806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('status', sa.Enum('draft', 'discarded', 'used_in_render', name='scriptstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'status')
    # ### end Alembic commands ###
