"""add settings to idea

Revision ID: e1d978b840c4
Revises: 1b17392c0e1d
Create Date: 2026-10-08 19:06:05.478247

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1d978b840c4"
down_revision: Union[str, Sequence[str], None] = "1b17392c0e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ideas", sa.Column("settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ideas", "settings")
    # ### end Alembic commands ###
