"""add schedule_config to channel

Revision ID: f6e5388d9d2d
Revises: e1d978b840c4
Create Date: 2026-10-08 19:21:13.827622

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6e5388d9d2d"
down_revision: Union[str, Sequence[str], None] = "e1d978b840c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("schedule_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "schedule_config")
    # ### end Alembic commands ###
