"""create_platform_connections

Revision ID: f891ae414827
Revises: d90c6b495b4e
Create Date: 2026-10-06 16:36:20.182110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f891ae414827"
down_revision: Union[str, Sequence[str], None] = "d90c6b495b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=True),
        sa.Column("account_name", sa.String(), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("platform_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_connections_platform"),
        "platform_connections",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_connections_user_id"),
        "platform_connections",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_instagram_connections_user_id"), table_name="instagram_connections"
    )
    op.drop_table("instagram_connections")
    op.drop_index(
        op.f("ix_youtube_connections_user_id"), table_name="youtube_connections"
    )
    op.drop_table("youtube_connections")
    op.drop_index(
        op.f("ix_tiktok_connections_user_id"), table_name="tiktok_connections"
    )
    op.drop_table("tiktok_connections")
    op.create_index(
        op.f("ix_publications_platform_connection_id"),
        "publications",
        ["platform_connection_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "publications",
        "platform_connections",
        ["platform_connection_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "publications", type_="foreignkey")
    op.drop_index(
        op.f("ix_publications_platform_connection_id"), table_name="publications"
    )
    op.create_table(
        "tiktok_connections",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("open_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("refresh_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("tiktok_connections_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tiktok_connections_pkey")),
    )
    op.create_index(
        op.f("ix_tiktok_connections_user_id"),
        "tiktok_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "youtube_connections",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("channel_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("channel_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("refresh_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("youtube_connections_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("youtube_connections_pkey")),
    )
    op.create_index(
        op.f("ix_youtube_connections_user_id"),
        "youtube_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "instagram_connections",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ig_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("instagram_connections_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("instagram_connections_pkey")),
    )
    op.create_index(
        op.f("ix_instagram_connections_user_id"),
        "instagram_connections",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_platform_connections_user_id"), table_name="platform_connections"
    )
    op.drop_index(
        op.f("ix_platform_connections_platform"), table_name="platform_connections"
    )
    op.drop_table("platform_connections")
    # ### end Alembic commands ###
